### ISSUE TITLE
API: Option to get api errors sent by email.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1137]
I have a custom form running. I would like to know if the api requests it makes to my D.T instance start failing.
- A log of D.T rest API errors in the wp-admin. 
- An email sent to the admin to look at the log.

**Comment by kodinkat** [comment]
Happy to pick up issue, capturing following requirement goals:

- Know when/why a form is not working
- Know why someone can't sign in on the mobile app
- A user is having trouble doing something in the theme or in the app. Having an admin visible error log would help a lot in debugging.
- Maybe catch errors caused by a version conflict between a server config, plugins and the theme that we didn't test.
