### ISSUE TITLE
Record name should not be able to left empty 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1144]
It should not be possible to have a record (contact, group, training etc. ) without text in the name field .

The image shows that it was possible to be done wherever editing was possible.

![Screenshot_20210127-020827.png](https://user-images.githubusercontent.com/43966676/105962460-782a9a80-6045-11eb-8fbd-048b0a068072.png)

**Comment by micahmills** [comment]
This is similar to #970. This caused a problem in lists because without a name the contact wasn’t clickable, but that is now fixed. 

I agree that in most cases a contact should have a name, but I could see a case where you don’t know a users name but know some other unique identifying characteristic (phone number of social media handle) in that case you might make a contact and not include their name until you know it later.

**Comment by mikeallbutt** [comment]
If the name field is empty, the record cannot be saved in the app.

**Comment by micahmills** [comment]
Ok then we should probably make the mobile app functionality match with the web version's. Can you make an issue on the mobile repo for this?

**Comment by micahmills** [comment]
We currently put up a Tool tip on the contacts/new page, but once the user is created you can click on their name in the top bar and edit it. This allows you to delete the name entirely and we need to show the same UI tooltip. 

as @corsacca mentioned we need to block this in the API as well so things aren't created without a name from a plugin.
