### ISSUE TITLE
List page: Names get truncated making it hard to distinguish the difference

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1191]
**Describe the bug**
When the user can't see the full name of a record and the record name is similar to other records, then it is difficult to work out which record is which.

**Expected behavior**
Show more of the name so that there is enough text to work out what the differences are between the record items.

**Screenshots**
![Screen Shot 2021-02-04 at 23 44 36](https://user-images.githubusercontent.com/43966676/106995162-e78a4380-6743-11eb-9f42-dcfedfadcf13.png)

**Desktop:**
 - OS: Mac 10.14.6 Mojave
 - Browser: latest Firefox

**Comment by micahmills** [comment]
So I looked into this a bit. This is directly related to how many columns you have showing in the list. If you have fewer columns it does show the whole name. There are ways to allow it to show multiple lines of text, but in my testing if the column is to narrow to show the full title it can also cause words to break funny so that a longer name starts on one line and ends on another. 

So the short answer is, I agree that truncated name is not ideal, but I think it is the best solution we have right now.
