### ISSUE TITLE
CMD/Ctrl + Click Broken

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#1211]
**Describe the bug**
As i look at the contact list or the group list, and want to open new tab in the browser with CMD/Ctrl + Click, it doesn’t work (the contact / group opens in the current tab). We have to use the right click. I tested this with Themes with version prior to v1.0, and it was all ok (the Cmd + Click was perfectly working). Right Clicking and opening in a new tab does work.

**To Reproduce**
1. From a Group or Contact list Cmd/Ctrl + Click to open in a new tab

**Expected behavior**
Open the Contact or Group record in a new tab

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [e.g. chrome, safari]: Chrome and Safari
 - Version [e.g. 22]: Most recent

**Additional context**
See https://disciple-tools.slack.com/archives/C01931CMU64/p1613042159026500 for the initial bug report from Josephine

**Comment by cairocoder01** [comment]
Looks like this mainly comes from the code that handles the click on the `tr` element, since it is not naturally recognized by the browser as being clickable:

```
// dt-assets/js/modular-list.js

$('#records-table').dragableColumns({
  ...
}).on('click', 'tbody tr', function(){
  window.location = $(this).data('link')
})
```

This always sets `window.location`, but you can detect if the user actually clicked the `<a>` inside the row and let the browser handle that naturally:

```
// dt-assets/js/modular-list.js

$('#records-table').dragableColumns({
  ...
}).on('click', 'tbody tr', function(evt){
  if (!evt.target.href) {
    window.location = $(this).data('link')
  }
})
```

However, if the user CMD+clicks elsewhere on the row, it is harder to recognize. I found this which is a fairly thorough yet slightly complex way of handling it by using separate keyup/keydown events: https://stackoverflow.com/a/16190994/92876. I think you could then use `window.open`, but that might act as a pop-up and be blocked by browsers. I'm not sure the correct way to open a new tab from javascript.

**Comment by corsacca** [comment]
Instead of listening for clicks on the whole row (tr) would could listen for clicks on each td excluding the name cell td.
