### ISSUE TITLE
Details tile enhancements - People Groups field icon, clearer separators between words, textarea for address field

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#1234]
1. The `people groups` field in the `details tile` for a group does not have an icon associated with it (but it used to in a previous version of the theme).

2. In the details info area: The text character to separate each people group should be like what is used for the locations field (a / symbol) and not the comma symbol (as this might be used for other purposes).

3. The `address field` (in the edit mode) doesn't use line breaks but should so that the address can be correctly displayed, and the address field is also not displaying on this record in the info section (at the top of the tile).

<img width="700" alt="Screen Shot 2021-03-15 at 00 47 21" src="https://user-images.githubusercontent.com/43966676/111114127-6d11c800-8528-11eb-995b-0d03efb72c11.png">

**Comment by micahmills** [comment]
![Screen Shot 2021-03-17 at 3 51 41 PM](https://user-images.githubusercontent.com/2531805/111470316-c7817300-8738-11eb-8ab4-d206233b0b50.png)

I am seeing the People Groups icon. If you aren't seeing it it might be a bug related to the specific browser so let us know a version you are using.

I think the multi-line address field will need a text area instead of a text input to show line breaks. We have issue #1049 for this and have it as a top priority.

We should be able to implement the slash instead of the comma pretty easily.
