### ISSUE TITLE
DT Contact 'Sources' field API bug

### ISSUE THREAD

**Issue by trip-nine** [DiscipleTools/disciple-tools-theme#1320]
Up until the last DT release you could add open ended inputs to the ‘Sources’ field via API…

I think with the newest release of DT, the Sources API was changed? 

And now there are limited input options for Source parameters..

Could this be opened back up?

I currently can’t send custom ‘sources’ tags to DT anymore through API..

<img width="3452" alt="DT API sources bug" src="https://user-images.githubusercontent.com/37304634/116121046-36ce7900-a68e-11eb-83a5-e849766e16f6.png">

**Comment by corsacca** [comment]
Hey.
Sources is a multi_select which are meant to be predefined before use. 
The API probably still accepts creating sources like tags.
Recently we push a fix that kept old (undefined) values to show up in a multi_select. This also affected tho sources field, making so the created sources don't show up on the front end.

We've just pulled in @cairocoder01 tags field type feature and the `campaigns` field. You might want to consider using that field instead of the sources field.

**Comment by corsacca** [comment]
I'll closed this issue at this point. Let us know if this does address the issue.
