### ISSUE TITLE
Make sure all emails are sent with the correct user locale

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1386]
Make sure that emails are sent in the user's language and not the sender's language or the system's language.

In `get_notification_message_html()` `get_notification_message_html` line ~872 there is code for switching to the user's language so that notifications are translated correctly.

This code needs to be abstracted out and applied to all emails and to email subject lines.

**Comment by micahmills** [comment]
I did a bit of digging here and the code that @corsacca mentioned on line 872 works for the notification emails, but the subject line isn't translated properly. `dt-notifications/notifications-email.php::dt_send_email_about_post()` gets the Post type label from `dt-posts/posts.php::get_label_for_post_type()` the `get_label_for_post_type` function pulls the names from the post_settings which uses the current users locale instead of the user who will receive the notification. These leaves you with a subject line that will have something like 'Disciple Tools: در Contact #19 بروزرسانی کنید' when Contact should be translated to the users language.

**Comment by squigglybob** [comment]
@corsacca where would be the best place to extract it to?
