### ISSUE TITLE
Font Icons no showing up

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#1959]
Money should show values
![image](https://user-images.githubusercontent.com/24901539/222087814-25e74207-3aa6-4e15-a66a-62982bb509f5.png)

**Comment by kodinkat** [comment]
@corsacca just looking into this and the reason why there are no hits for the `money` query string, is because the backend stylesheet does not contain any matching icons - see attached screenshot below:

![Screenshot 2023-03-01 at 10 55 11](https://user-images.githubusercontent.com/19330800/222121097-048cab8d-4b76-4f7e-8b83-d40bebab3b50.png)

**Comment by corsacca** [comment]
Sorry, i was too hasty in creating this issue.
`cash` and `currency` do show up.
