### ISSUE TITLE
Login Features and performance.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#2210]
https://github.com/DiscipleTools/disciple-tools-theme/blob/d5080722f4e9fc4cd8d65b9ff9cb1c76f34fcc4a/dt-login/login-page.php#L21

These lines run on every single request, loading all WP Login fields, D.T roles, etc every time.
Is there a way to simplify?

**Comment by squigglybob** [comment]
I have reduced the writes to the database every time DT_Login_Fields is called.  as if the number of fields hasn't changed nothing needs to be written in `parse_and_save_fields`.

The DT roles should be using the cache.
Do you have any thoughts on other ways to simplify?

I think in order to simplify we would have to look at the whole strategy of default field values, and how to propogate changes of those to main site and subsites etc. etc.

**Comment by corsacca** [comment]
One issue: only the "is enabled" part needs to be loaded at this stage, not all fields and roles.
If sso is not enabled, then we don't need to build the rest.
This is run before plugins and done loading, so the roles list isn't completed, but gets cached.

> I think in order to simplify we would have to look at the whole strategy of default field values, and how to propogate changes of those to main site and subsites etc. 

This does make it hard.
