### ISSUE TITLE
Contact: add subassigned under connections

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#429]

**Comment by mikeallbutt** [comment]
What is meant by "add subassigned under connections". Does that mean move the field to the connections tile, or does it mean when a contact is subassigned, they also get connected to this user?

**Comment by corsacca** [comment]
Would be a list of all the contacts that contact is subassigned to. 
The list could be in the connections tile.

**Comment by ahillbilly** [comment]
Currently, 
if Contact A is connected to Contact B in Contact B's "Connections to People" field, then Contact B is also automatically listed as a connection in Contact A's "Connections to People" field.

if Group X is connected to Contact A in Contact A's "Groups" field, then Contact A is also automatically listed as a member in Group X's "Member List".

This issue proposal is that when Contact A is added as "Sub-Assigned" on Contact B and Contact C and Contact D, that Contact B, C & D would show up listed in a new connection field on Contact A's record so that a User could see all the contacts that Contact A has this responsibility for.

**Comment by corsacca** [comment]
Closed by https://github.com/DiscipleTools/disciple-tools-theme/commit/2226cc14efc39b95b514d72ec3e8bd4e06b2c72b
