### ISSUE TITLE
Personal tag system for flagging and organizing contacts.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#567]
To be separate from the global tagging system.

**Comment by ChrisChasm** [comment]
@corsacca How far is this feature. I know we launched this feature.

**Comment by micahmills** [comment]
Having a separate tagging system could lead to some confusing UI. We would think about how to do this so that it was clear to the user that this was a personal tag not a global tag. 

We have another feature request to favorite, star or pin contacts and groups (#402 ) would that offer a similar functionality without the UI confusion?

**Comment by corsacca** [comment]
The goal is to un-lock our power users to sort and organize the contacts and they see fit. Since they are multipliers they don't have access to create their own fields, tags seem like an obvious first step. 
I think #402 would be cool, but i bit too simplistic.

Our admins have also expressed the desire to "clean the tags list up", which wouldn't be good if multipliers are using tags personally.

**Comment by micahmills** [comment]
Now that we have private fields and tags as a custom field option. Is there anything else we need to do for this issues?
