### ISSUE TITLE
Can we @mention someone while editing a comment?

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#568]

**Comment by ahillbilly** [comment]
@mikeallbutt, meaning that you want to be able to add the @mention when editing the comment, correct?

**Comment by mikeallbutt** [comment]
> @mikeallbutt, meaning that you want to be able to add the @mention when editing the comment, correct?

Correct. It would be nice to have a way to mention/tag a contact/group when writing a comment.
This might be done like what the issue #1041  describes too.

Maybe #@contact would work for a contact and #@# for groups (since they will never be a contact so don't really need a mention - just a tag to create a link to them). 

So typing @mention would indicate you were looking for a DT user but #@contact would show contacts and not just users - but users if they are contacts could list too.

The list displayed would need to indicate that the user has or doesn't have access (is or isn't shared to them or not) to the contact or group.

Also, on an english keyboard, the @ key and # key are next to each other so it wouldn't be too hard to type.

**Comment by ahillbilly** [comment]
I like this idea.  I think it might be a large project that would require a shift from the current @mentioning of users.  It would allow links to other records more freely.

**Comment by corsacca** [comment]
To keep the UI and experience simple we'd like to keep notifications (and therefore @mentions) to come only from new comments.
