### ISSUE TITLE
Notes section on groups and contacts

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#655]
We want the user to be able to write notes on a contact or a group.
Notes can be personal or public to those who have access to the record. No one other than the user who wrote the personal note can see the note.
This can be achieved by a notes tile, a note comment type, or a whole new section for notes.

**Comment by mikeallbutt** [comment]
This could also be achieved by making a comment as a "sticky" so that very important notes could be seen under the users contact details area.

**Comment by mikeallbutt** [comment]
One option would be having the ability to "Pin" comments. This would allow people to use the standard commenting system. The pinned comments would then be available (and editable if need be). But that creates the issue that the comment was edited and so that an initial comment gets changed and no longer reflects what it first said - unless there was a way to view the original/past comments.

All that seems to complicated, so just adding a new area specifically for a note for the contact or group would be easiest IMO.

**Comment by corsacca** [comment]
See issue https://github.com/DiscipleTools/disciple-tools-theme/issues/1270 on creating private fields.

**Comment by micahmills** [comment]
With the Private Notes and Textarea field type complete I think this is done. The user can create a Tile and a private text field to keep private notes on a group or contact. 

I am going to close this for now, @corsacca if you think it needs to be looked at again we can reopen it.

**Comment by mikeallbutt** [comment]
Having this note field included in a standard install of DT would be useful to many I think.

**Comment by corsacca** [comment]
We plan to test this internally, and we recommend other do too. If we find something that works well we can consider moving it to core.
