### ISSUE TITLE
Record languages spoken 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#775]
It might be helpful to have a multi-select field offering different languages that the contact speaks (or their preferred language) so they can be connected to someone from their language. Setting a default language of the DT instance would aide the completion of filling in the records well.

**Comment by corsacca** [comment]
@mikeallbutt this a great suggestion. We have tested it in the past and found the field didn't add value in dispatching as the media source for our contacts didn't provide a language. When a contact would come who spoke a different language it would be evident by their messages to us.
A language selector will be useful in contexts where their ins't a majority language, of it the D.T instance is used for more that one language region. 
In that can the preferred language is a great option for the custom fields. It is actually the example field in the started plugin: https://github.com/DiscipleTools/disciple-tools-theme/wiki/Adding-fields
We want to keep the interface of the contact record as simple as possible, yet as customizable as possible. Each group will have individual needs and we benefit from creating custom fields.
Thanks for your suggestion.

**Comment by mikeallbutt** [comment]
@ahillbilly I would like to have this issue reopened. In DT now a users preferred language is now able to be recorded, so using the same field would be good. 
If the desire is that many contacts become users, then having their language set when they are converted from a contact to a user will be helpful, so that DT sends out to them system messages in the appropriate language.

**Comment by corsacca** [comment]
@mikeallbutt  Hey, Are you talking about the interface language or the "Languages you are comfortable speaking " field? 
Being able to set a language (with the default already set) when a user is created might be a good request for a new isssue.

**Comment by ahillbilly** [comment]
@mikeallbutt this was last closed acknowledging that custom fields would address an instance's issue of desiring to record contacts' language spoken.  I still see it as complete in addressing this issue.  I agree with @corsacca that this would make a good request for a new issue.  

In my mind, it is better to let the contact (new user) set the languages that they are comfortable working in rather than taking another user's perspective/assessment as authoritative.  With that in mind, it could be better to introduce an issue more in the realm of a new user questionairre that would push/urge a new user to update this than to port data into the user record that might not be correct from the user's perspective.
