### ISSUE TITLE
Create new user fields auto filled

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#807]
When a user wants to create another new user by using the dispatcher action of "Make a new user from this contact", the modal that pops up fills the Display Name field but not the Email field. The email of the contact (if set) could be used to auto-populate the Email field.

<img width="538" alt="Screenshot 2019-10-28 19 01 30" src="https://user-images.githubusercontent.com/43966676/67729203-ccb01780-f9b5-11e9-8c1d-e3fac15bea19.png">

**Comment by corsacca** [comment]
This modal is present on the contact record page page. 
Admin Actions > "Make a user from this contact"

**Comment by micahmills** [comment]
This issue is fixed by PR #1238. 

One caveat is that this field is filled at page load, so if you load the page, edit the Email field, then select "make a user from this contact" the field will have the old data. 

@corsacca do you think we should close this issue or try to fix it so that the email field dynamically updates if the user updates?

**Comment by corsacca** [comment]
Good question @micahmills! I think it will be good as it is.
