### ISSUE TITLE
Metrics page errors when group data loops

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-theme#817]
If there is a infinite loop in the group parent/child tree then the metrics page will error and just display:
![image](https://user-images.githubusercontent.com/24901539/67874206-e6c43400-fb34-11e9-9230-a8985861d08a.png)

**Comment by mikeallbutt** [comment]
In my instance a loop has been created and I get this message:

Error setting up the graph
This can be caused by circular connection data. Check that no child has two parents that are related. A group and a grand child group can't both be the parent of another group. 

There needs to be a check to prevent this loop from being set, or more details as to what group is causing the loop so that it can be fixed.

**Comment by corsacca** [comment]
The user will now get a message pointing them to the loop.
![image](https://user-images.githubusercontent.com/24901539/107237248-d03ea500-6a26-11eb-854d-a98528b8b63b.png)
