### ISSUE TITLE
View Leaders

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#846]
DT can designate someone as a leader of a group but there is no way to gather a list of leaders of groups.

Having a filter preset might be an option.

**Comment by corsacca** [comment]
@mikeallbutt i don't think i disagree with you. Please elaborate more on the use case

**Comment by mikeallbutt** [comment]
> Please elaborate more on the use case.

I have many groups and each group has a leader or 2. I want to invest in these leaders who in turn invest in the group members. I need a list of the leaders.

**Comment by mikeallbutt** [comment]
@corsacca have you got any more thoughts on how this might be able to be implemented?

**Comment by mikeallbutt** [comment]
@corsacca and @ahillbilly Having a filter to be able to see who leaders would be a possible first step to access this information. At present I don't thing there is anyway to see which contacts have been designated as group leaders.

**Comment by ahillbilly** [comment]
This data isn't currently saved on the contact records of the group members, but is saved in the group record.  We will need a function to add this data from the group record/interface to the contact record so that it will then make the contacts filterable by this data.  It would probably be a good idea to work this into the contact record interface as well.

**Comment by mikeallbutt** [comment]
Another idea would be to have a contact filter that shows who are assigned as `Group Coach / Church Planter`.

@ahillbilly what do you think?

**Comment by corsacca** [comment]
I'm merging a couple issues into a common one that address them all: https://github.com/DiscipleTools/disciple-tools-theme/issues/1286
