### ISSUE TITLE
Download contacts info to your address book

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#943]
Had a request to easily add the users data into a contact card so the person can easily contact the user from their phone without having to manually entering phone numbers or copy and pasting data.

**Comment by corsacca** [comment]
Maybe something for the mobile app? A button to create a contact card in your address book from this contact record. (share?).
Does that sound right?
I think the phone numbers should be clickable (https://github.com/DiscipleTools/disciple-tools-theme/issues/479)

**Comment by micahmills** [comment]
Yes this is what I am thinking. I am researching the possibility of making a vCard server side that can be downloaded. Then the browser/OS can import that into the address book. 

The phone numbers are clickable, but that defaults to calling the person (at least in iOS). Often we are not calling people on the phone at first. We usually wants to send a message in WhatsApp or Telegram or text message first. This means they have to copy the phone number or Telegram username and create a contact in their phone or desktop app to send them a message. 

Having a "click to add to your address book" button would make that a little easier.

**Comment by yeshu-davit** [comment]
At [one point](https://github.com/DiscipleTools/disciple-tools-theme/commit/658219b81e2627afa873f7b8307fcf1d82391fe5) there was a feature for one-click "open in whatsapp" for phone numbers, but it seems to have been lost somewhere along the line since then. Maybe bringing something like that back is an option?

Phone numbers could have icons for the different chat platforms so users could check each platform at a click?

**WhatsApp**\
`https://api.whatsapp.com/send?phone=[PHONE]`

**Signal**\
`https://signal.me/#p/[PHONE]`

Seem's like that option [isn't available](https://stackoverflow.com/questions/54251613/how-to-create-a-link-to-contact-specific-phone-number-via-telegram) for Telegram, unfortunately...

All that said, I also love the idea of vCards.

This might be too intense for most users, but I'll throw it out there:

What about integrating CardDAV? Users could have their entire contacts list get updated right on their devices as soon as there are any changes, and they could use their native contacts management to see what contacts have what chat platforms.

**Comment by corsacca** [comment]
@yeshu-davit the mobile app has some of the linking functionality
And import from contacts list: https://github.com/DiscipleTools/disciple-tools-mobile-app/issues/582
Have you had a change to check it out?
https://disciple.tools/download-mobile-app/

**Comment by micahmills** [comment]
We have merged #1553 which adds the option to open a phone number in any number of messaging services. That largely solves this problem because it makes it easy to message someone. We can still consider the vCard thing, but I don't think it is as necessary now.

**Comment by corsacca** [comment]
Shall we move to close this issue then?

**Comment by micahmills** [comment]
If there is a reason to keep it open we can reopen it but, I am ok with closing it.
