### ISSUE TITLE
Sources list not localized

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-theme#969]
The list of sources as well as the "Sources" heading in the contact edit modal are not showing up in the localize language.

**Comment by corsacca** [comment]
The field label is being overwritten by the $custom_field_options line:714 of dt-contacts/contacts-post-type.php
The source options are being loaded from the options table. This is because we did sources differently before, it does not need to be an wp_option any more. I think it can be moved directly to the field defaults array. Will need to check for dependencies.

**Comment by corsacca** [comment]
Fixed with: https://github.com/DiscipleTools/disciple-tools-theme/commit/da873d518a3789d2fdd1acf53d251708532adcca
You may need to delete the custom label for the sources field name.
That is now possible with: https://github.com/DiscipleTools/disciple-tools-theme/commit/afd6128a365dfcbf03754cf4555c1e9b3e2b234f

Quick link: {domain}/wp-admin/admin.php?page=dt_options&tab=custom-fields&field-select=contacts_sources (this link will work when these commits are reeased)
